### PR TITLE
Create Palindrome_Checker.py

### LINKED ISSUE #12: Palindrome Checker (One-liner)
directory containing some curated python programs, 
if yes, Kindly add under hacktoberfest

### PR DESCRIPTION
**Pull request by Yogeshkarma**
Added Palindrome_Checker.py
Closes #12

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@Yogeshkarma Add more.. it's too less

**Comment by Yogeshkarma** [comment]
@J-B-Mugundh are you talking about the number of programs

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh are you talking about the number of programs

Yeah

**Comment by Yogeshkarma** [comment]
@J-B-Mugundh actually one of my friend , added a lot of program under a single issue. so his PR got excluded,
that is why i added one just to verify .then will add more with other issues

**Comment by J-B-Mugundh** [comment]
@Yogeshkarma That would be an issue with the repository. You could add a lot. Try to add atleast 10 programs as a folder and raise the PR again!

**Pull request closed without merging**
